version: "3.9"
services:
  mysql8:
    image: mysql:8
    security_opt:
      - apparmor:unconfined
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: batoicine
      MYSQL_USER: batoi
      MYSQL_PASSWORD: 1234
  batoiflix_app:
    depends_on:
      - mysql8
    build: .
    image: batoiflix:v1.0
    ports:
      - "80:5000"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8/batoicine?&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: batoi
      SPRING_DATASOURCE_PASSWORD: 1234
      LOGGING_LEVEL_ROOT: WARN
      SERVER_PORT: 5000
volumes:
  db_data: